### ISSUE TITLE
Application crashed!

### ISSUE THREAD

**Issue by S2606** [fossasia/query-server#435]
**I'm submitting a ...**
- [X] bug report
- [ ] feature request

**Current behavior:**
Application is crashed

**Expected behavior:**
It shouldnt be.

**Steps to reproduce:**

**Comment by S2606** [comment]
I would love to claim this but since i dont have access to Heroku deployment, I cant

**Comment by S2606** [comment]
@vaibhavsingh97 @bhaveshAn @cclauss What do you think?

**Comment by bhaveshAn** [comment]
Here are the logs

Screenshot: 
![screenshot from 2018-01-11 14-19-13](https://user-images.githubusercontent.com/22936570/34816332-a510bdfe-f6da-11e7-88d5-5fe830d1195a.png)

Complete logs : 
```
2018-01-11T08:46:59.666668+00:00 heroku[web.1]: State changed from crashed to starting

2018-01-11T08:47:09.009725+00:00 app[web.1]: Traceback (most recent call last):

2018-01-11T08:47:09.009745+00:00 app[web.1]:   File "app/server.py", line 9, in <module>

2018-01-11T08:47:09.009750+00:00 app[web.1]:     from query_cache import lookup, store

2018-01-11T08:47:09.009751+00:00 app[web.1]:   File "/app/app/query_cache.py", line 25, in <module>

2018-01-11T08:47:09.009752+00:00 app[web.1]:     db.create_index([('createdAt', DESCENDING)], expireAfterSeconds=60 * 60 * 24)

2018-01-11T08:47:09.009753+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/collection.py", line 1753, in create_index

2018-01-11T08:47:09.010000+00:00 app[web.1]:     self.__create_index(keys, kwargs, session, **cmd_options)

2018-01-11T08:47:09.010002+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/collection.py", line 1655, in __create_index

2018-01-11T08:47:09.010240+00:00 app[web.1]:     session=session)

2018-01-11T08:47:09.010241+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/collection.py", line 244, in _command

2018-01-11T08:47:09.010298+00:00 app[web.1]:     retryable_write=retryable_write)

2018-01-11T08:47:09.010299+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/pool.py", line 496, in command

2018-01-11T08:47:09.010379+00:00 app[web.1]:     collation=collation)

2018-01-11T08:47:09.010381+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/network.py", line 125, in command

2018-01-11T08:47:09.010418+00:00 app[web.1]:     parse_write_concern_error=parse_write_concern_error)

2018-01-11T08:47:09.010420+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/pymongo/helpers.py", line 146, in _check_command_response

2018-01-11T08:47:09.010462+00:00 app[web.1]:     raise OperationFailure(msg % errmsg, code, response)

2018-01-11T08:47:09.010505+00:00 app[web.1]: pymongo.errors.OperationFailure: not authorized on query-server-v2 to execute command { createIndexes: "queries", indexes: [ { name: "createdAt_-1", key: { createdAt: -1 }, expireAfterSeconds: 86400 } ], writeConcern: {} }

2018-01-11T08:47:09.599646+00:00 heroku[web.1]: Process exited with status 1

2018-01-11T08:47:09.614016+00:00 heroku[web.1]: State changed from starting to crashed

2018-01-11T08:47:06.407289+00:00 heroku[web.1]: Starting process with command `python app/server.py`

2018-01-11T08:47:11.827819+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=query-server.herokuapp.com request_id=fcb9d125-fa72-4405-a3fc-35f1ca72abc9 fwd="14.139.229.43" dyno= connect= service= status=503 bytes= protocol=https

```

**Comment by cclauss** [comment]
Looks like this one is mine...  Sorry!  Fix on its way.

**Comment by S2606** [comment]
@cclauss I would like to work on this.

**Comment by cclauss** [comment]
@S2606 Please see #437 and help out.  Perhaps that PR does not solve the root problem.  I do not know Mongo so your help would be much appreciated.
